name: 'Enable Qt Tools'
description: 'Adds Qt build tools to the environment'

inputs:
  qtdir:
    description: 'The directory where Qt is installed'

  tools:
    description: 'The tools to enable'
    required: true

runs:
  using: 'node12'
  main: 'action.js'
